services:
  dvc-xavinhhoa-staging2:
    image: nducminhekila/dvc-xavinhhoa-staging2
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.services.dvc-xavinhhoa-staging2.loadbalancer.server.port=1337
      - traefik.http.routers.dvc-xavinhhoa-staging2.rule=Host(`dvc-xvh.ekila.vn`)
      - traefik.http.routers.dvc-xavinhhoa-staging2.entrypoints=websecure
      - traefik.http.routers.dvc-xavinhhoa-staging2.tls=true
      - traefik.http.routers.dvc-xavinhhoa-staging2.tls.certresolver=letsencrypt
      - traefik.http.routers.dvc-xavinhhoa-staging2.middlewares=request-limit@file
    env_file: .env
    volumes:
      - ./public:/opt/app/public

networks:
  proxy:
    external: true
