services:
  dvc-xatanlac-staging:
    image: nducminhekila/dvc-xatanlac-staging
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.services.dvc-xatanlac-staging.loadbalancer.server.port=1337
      - traefik.http.routers.dvc-xatanlac-staging.rule=Host(`tanlac.sohoaqg.vn`)
      - traefik.http.routers.dvc-xatanlac-staging.entrypoints=websecure
      - traefik.http.routers.dvc-xatanlac-staging.tls=true
      - traefik.http.routers.dvc-xatanlac-staging.tls.certresolver=letsencrypt
      - traefik.http.routers.dvc-xatanlac-staging.middlewares=request-limit@file
    env_file: .env
    volumes:
      - ./public:/opt/app/public

networks:
  proxy:
    external: true
