services:
  dvc-xatanlac:
    image: ekilaadmin/dvc-xatanlac
    networks:
      - proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.services.dvc-xatanlac.loadbalancer.server.port=1337
      - traefik.http.routers.dvc-xatanlac.rule=Host(`tanlac.sohoaqg.vn`)
      - traefik.http.routers.dvc-xatanlac.entrypoints=websecure
      - traefik.http.routers.dvc-xatanlac.tls=true
      - traefik.http.routers.dvc-xatanlac.tls.certresolver=letsencrypt
      - traefik.http.routers.dvc-xatanlac.middlewares=request-limit@file
    env_file: .env
    volumes:
      - ./public:/opt/app/public

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    image: ekilaadmin/dvc-bk
    container_name: backup_container

networks:
  proxy:
    external: true
